In [2]:
from sklearn import datasets
from abupy import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from abupy import AbuML

# 数据集
scikit_boston = datasets.load_boston()
x = scikit_boston.data
y = scikit_boston.target
df = pd.DataFrame(data=np.c_[x, y], columns=np.append(scikit_boston.feature_names, ['MEDV']))
df.head(1)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.0063,18.0,2.31,0.0,0.538,6.575,65.2,4.09,1.0,296.0,15.3,396.9,4.98,24.0

In [3]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

# 归一化数据
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

# 模型训练
df = pd.DataFrame(data=np.c_[x_train, y_train], columns=np.append(scikit_boston.feature_names, ['MEDV']))
boston = AbuML(x_train, y_train, df)
boston.estimator.polynomial_regression(degree=1)
reg = boston.fit()

In [8]:
# 测试集上预测
y_pred = reg.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.58817038488454432

In [8]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-0.4066,2.0345,-1.1871,-0.2933,-1.2941,0.7240,-2.0903,1.0896,-0.9837,-0.8563,-1.3311,0.3950,-1.0471,31.1
1,-0.3955,-0.4962,-0.1542,-0.2933,-0.0436,-0.5188,0.8860,-0.7108,-0.4106,0.1363,-0.2955,0.4133,0.5019,18.8
2,-0.3970,-0.4962,0.1259,-0.2933,0.1791,0.7155,0.7569,-0.6943,-0.9837,-0.8087,1.2108,0.3959,-0.8462,22.0
3,-0.4011,-0.4962,2.1275,-0.2933,0.2476,-0.3913,0.5704,-0.7835,-0.8691,-1.3140,0.3165,0.2137,0.2331,20.3
4,1.6581,-0.4962,1.0260,-0.2933,0.3846,-2.3191,1.1406,-1.0832,1.6528,1.5272,0.8342,-3.8150,3.0179,17.9
5,-0.4014,-0.4962,2.1275,-0.2933,0.2476,-0.5790,0.0540,-0.7554,-0.8691,-1.3140,0.3165,0.3463,0.2469,22.0
6,-0.4013,-0.4962,-1.0237,-0.2933,-0.3605,-0.3688,-0.7528,-0.1513,-0.5252,-0.6720,-0.8603,0.3934,-0.3433,23.2
7,-0.3950,0.7692,-0.8953,-0.2933,-1.0629,0.1537,-2.1656,1.4695,-0.4106,-0.6483,-0.8603,0.1795,-1.0249,23.7
8,-0.3518,-0.4962,-0.7100,3.4095,-0.3862,0.4872,0.2979,0.1249,-0.1813,-0.6066,-0.4838,0.3382,-0.4223,25.1
9,-0.3685,0.4317,-0.7596,-0.2933,-1.0372,2.7680,-2.1441,2.3409,-0.2959,-0.4699,0.3165,0.4358,-1.2535,42.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0.1132,-0.4962,1.0260,-0.2933,1.3782,0.3387,0.6565,-0.6725,1.6528,1.5272,0.8342,-3.5594,0.7679,14.1
395,-0.3936,0.4317,-0.7596,-0.2933,-1.0372,0.2854,-1.9792,1.6377,-0.2959,-0.4699,0.3165,0.4286,-0.9266,24.4
396,-0.3208,-0.4962,-0.4270,-0.2933,-0.1207,-1.1590,-1.1329,-0.0388,-0.6398,-0.6066,1.2108,-0.8103,-0.1244,20.2
397,-0.3889,-0.4962,2.4324,-0.2933,0.4874,-1.2179,1.0796,-0.9893,-0.6398,1.7947,0.7872,-0.1745,1.5770,7.0
398,-0.3389,-0.4962,-0.4270,-0.2933,-0.1207,-0.2624,0.5847,0.2711,-0.6398,-0.6066,1.2108,0.2409,-0.3225,18.2
399,-0.4040,-0.4962,0.1259,-0.2933,0.1791,-0.2287,0.3050,-0.7415,-0.9837,-0.8087,1.2108,0.4358,-0.4860,20.6
400,-0.3995,1.4018,-1.1127,-0.2933,-0.9858,1.2535,-1.5022,1.2108,-0.5252,-0.0658,-1.5193,0.3618,-1.3464,36.4
401,-0.3458,-0.4962,-0.7100,-0.2933,-0.3862,2.8773,0.1831,-0.0193,-0.1813,-0.6066,-0.4838,0.3089,-1.4018,41.7
402,-0.3964,0.3474,-0.5992,-0.2933,-0.7545,0.3569,-0.3404,0.0175,-0.7545,-1.1059,0.0811,0.4134,-0.6730,24.4
403,-0.4071,3.5107,-1.4001,-0.2933,-1.2770,1.1933,-1.9469,1.7573,-0.7545,-0.0420,-0.6721,0.2903,-1.1275,32.9

In [7]:
df[].as_matrix()

array([[ -0.4066,   2.0345,  -1.1871, ...,   0.395 ,  -1.0471,  31.1   ],
       [ -0.3955,  -0.4962,  -0.1542, ...,   0.4133,   0.5019,  18.8   ],
       [ -0.397 ,  -0.4962,   0.1259, ...,   0.3959,  -0.8462,  22.    ],
       ...,
       [ -0.3458,  -0.4962,  -0.71  , ...,   0.3089,  -1.4018,  41.7   ],
       [ -0.3964,   0.3474,  -0.5992, ...,   0.4134,  -0.673 ,  24.4   ],
       [ -0.4071,   3.5107,  -1.4001, ...,   0.2903,  -1.1275,  32.9   ]])